### ISSUE TITLE
First Major Release v1.0.0

### ISSUE THREAD

**Issue by indrajithi** [indrajithi/tiny-web-crawler#24]
This is a place holder Issue for the first major release [v1.0.0](https://github.com/indrajithi/tiny-web-crawler/milestones) 

**Please feel free to crease issue from this list**

### Functional Requirements

- [x] Basic Crawling Functionality #1 
- [x] Configurable options for maximum links to crawl #1 
- [x] Handle both relative and absolute URLs #1 
- [x] Save crawl results to a specified file #1 
- [x] Configurable verbosity levels for logging #7 
- [x] Concurrency and custom delay #7 
- [x] Support Regular expression #16 
- [ ] Crawl internal / external links only
- [ ] Return optional html in response #19 
- [ ] Crawl depth per website/domain
- [ ] Logging
- [x] Retry mechanism for transient errors
- [ ] (optional) Support Javascript heavy dynamic websites
- [ ] (Optional) Respect Robots.txt
- [ ] (Optional) User-Agent Customization
- [ ] (Optional) Proxy support
- [ ] (Optional) Use Asynchronous I/O

### Non Functional Requirements

- [X] Git workflow for CI/CD
- [ ] Documentation (API and Developer)
- [ ] Test coverage above 80%
- [ ] Git hooks
- [ ] Modular and Extensible Architecture #17 
- [ ] (Optional) Memory Benchmark: Monitor Monitor memory usage during the crawling process
- [ ] (optional) Security considerations (e.g., handling of malicious content)

**Comment by Mews** [comment]
You forgot to check "Return optional html in response https://github.com/indrajithi/tiny-web-crawler/pull/19" ;)

**Comment by Mews** [comment]
@indrajithi On `Git hooks` maybe you should link my second pr on that feature (#25 ) so people also see the `pre-commit install --hook-type pre-push` command :)

**Comment by Mews** [comment]
@indrajithi you can check "Test coverage above 80%" now ;)
